=== AlphaWallet/Tokenscript/schema/tokenscript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://tokenscript.org/2019/05/tokenscript"
           xmlns:xhtml="http://www.w3.org/1999/xhtml"
           xmlns="http://tokenscript.org/2019/05/tokenscript">


  <!-- Importing XML namespace for xml:lang and xml:id -->
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="xml.xsd" />

  <!-- Importing XML Signature namespace. Schema is from
      http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd
  -->
  <xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
        schemaLocation="xmldsig-core-schema.xsd" />

  <!-- Importing XHTML namespace. use xhtml1-strict.xsd to get xhtml:Block -->
  <xs:import namespace="http://www.w3.org/1999/xhtml"
             schemaLocation="xhtml1-strict.xsd"/>
  <xs:element name="token">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="contract"/>
        <xs:element ref="origins"/>
        <xs:element minOccurs="0" ref="selections"/>
        <xs:element ref="cards"/>
        <xs:element minOccurs="0" ref="grouping"/>
        <xs:element minOccurs="0" ref="ordering"/>
        <xs:element ref="attribute-types"/>
      </xs:sequence>
      <xs:attribute name="custodian" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="text"/>
  <xs:complexType name="text" mixed="true">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="plurals"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="plurals">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="string"/>
      </xs:sequence>
      <xs:attribute use="required" ref="xml:lang"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="string">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute ref="xml:lang"/>
          <xs:attribute name="quantity" type="quantity"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="quantity">
    <xs:restriction base="xs:string">
      <xs:enumeration value="zero" />
      <xs:enumeration value="one" />
      <xs:enumeration value="two" />
      <xs:enumeration value="few" />
      <xs:enumeration value="many" />
      <xs:enumeration value="other" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="contract">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="address">
          <xs:complexType mixed="true">
            <xs:attribute name="network" use="required" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" ref="interface"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:ID"/>
      <xs:attribute name="interface" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="interface" type="xs:NCName"/>
  <xs:element name="cards">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="token-card"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="action"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="token-card">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="xhtml:style"/>
        <xs:element ref="view-iconified"/>
        <xs:element ref="view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="action">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element minOccurs="0" ref="attribute-type"/>
        <xs:element minOccurs="0" ref="transaction"/>
        <xs:element minOccurs="0" ref="exclude"/>
        <xs:element minOccurs="0" ref="xhtml:style"/>
        <xs:element ref="view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="include" type="xs:NCName"/>
  <xs:element name="view" type="shtml"/>
  <xs:element name="view-iconified" type="shtml">
  </xs:element>
  <xs:complexType name="shtml">
    <xs:complexContent>
      <xs:extension base="xhtml:Block">
        <xs:attributeGroup ref="xhtml:attrs"/>
        <xs:attribute name="onload" type="xhtml:Script"/>
        <xs:attribute name="onunload" type="xhtml:Script"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="redeem">
    <xs:complexType>
      <xs:attribute name="format" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="exclude">
    <xs:complexType>
      <xs:attribute name="selection"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="feemaster" type="xs:anyURI"/>
  <xs:element name="gateway" type="xs:anyURI"/>
  <xs:element name="prefix" type="xs:anyURI"/>
  <xs:element name="selections">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="selection"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="selection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="filter"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="filter" type="xs:string"/>
  <xs:element name="grouping">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="group"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="consecutive_groups"/>
      </xs:sequence>
      <xs:attribute name="bitmask" use="required"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="consecutive_groups">
    <xs:complexType/>
  </xs:element>
  <xs:element name="ordering">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="order"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="order">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="byName"/>
        <xs:element maxOccurs="unbounded" ref="byValue"/>
      </xs:sequence>
      <xs:attribute name="bitmask" use="required"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="byName">
    <xs:complexType>
      <xs:attribute name="field" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="byValue">
    <xs:complexType>
      <xs:attribute name="field" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute-types">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="attribute-type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute-type">
    <xs:complexType>
      <xs:sequence>
        <!-- name is not needed if the attribute is only used for selection -->
        <xs:element minOccurs="0" ref="name"/>
        <xs:element ref="origins"/>
        <xs:element minOccurs="0" ref="mapping"/>
      </xs:sequence>
      <xs:attribute name="as" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="oid" type="xs:NMTOKEN"/>
      <xs:attribute name="syntax" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="transaction">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element ref="ethereum"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="origins">
    <xs:complexType>
      <xs:all>
        <xs:element minOccurs="0" ref="ethereum"/>
        <xs:element minOccurs="0" ref="user-entry"/>
        <xs:element minOccurs="0" ref="token-id"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="user-entry">
    <xs:complexType>
      <xs:attribute name="as" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="token-id">
    <xs:complexType>
      <xs:attribute name="as" type="xs:NCName"/>
      <xs:attribute name="bitmask"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ethereum">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="inputs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="uint256">
                <xs:complexType >
                  <xs:attribute name="ref" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="contract" type="xs:IDREF"/>
      <xs:attribute name="function" type="xs:NCName"/>
      <xs:attribute name="as" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="option">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="value">
                <xs:complexType mixed="true">
                  <xs:attribute ref="xml:lang"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" use="required" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlphaWallet/Tokenscript/examples/devcon5-nft/Devcon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ts:token xmlns:ts="http://tokenscript.org/2019/10/tokenscript"
          xmlns="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://tokenscript.org/2019/10/tokenscript http://tokenscript.org/2019/10/tokenscript.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          custodian="false"
>
  <ts:name>
    <ts:plurals xml:lang="en">
      <ts:string quantity="one">Devcon5 Ticket</ts:string>
      <ts:string quantity="other">Devcon5 Tickets</ts:string>
    </ts:plurals>
    <ts:plurals xml:lang="es">
      <ts:string quantity="one">Boleto de admisión</ts:string>
      <ts:string quantity="other">Boleto de admisiónes</ts:string>
    </ts:plurals>
    <ts:plurals xml:lang="zh">
      <ts:string quantity="one">入場券</ts:string>
      <ts:string quantity="other">入場券</ts:string>
    </ts:plurals>
  </ts:name>
  <ts:contract interface="erc875" name="Devcon5">
    <ts:address network="1">0x48401d879E7736Ab80D3D18E24cEbcAc5345170A</ts:address>
  </ts:contract>
  <ts:origins>
    <!-- Define the contract which holds the token that the user will use -->
    <ts:ethereum contract="Devcon5">
    </ts:ethereum>
  </ts:origins>
  <ts:selections>
    <ts:selection id="expired">
      <ts:name>
        <ts:plurals xml:lang="en">
          <ts:string quantity="one">Expired Ticket</ts:string>
          <ts:string quantity="other">Expired Tickets</ts:string>
        </ts:plurals>
        <ts:string xml:lang="zh">已经过期的票</ts:string>
      </ts:name>
      <ts:filter>expired</ts:filter>
    </ts:selection>
  </ts:selections>
  <ts:cards>
  </ts:cards>

  <ts:attribute-types>
    <ts:attribute-type id="category" syntax="1.3.6.1.4.1.1466.115.121.1.15">
    <ts:name>
      <ts:string xml:lang="en">Cat</ts:string>
      <ts:string xml:lang="zh">等级</ts:string>
      <ts:string xml:lang="es">Cat</ts:string>
    </ts:name>
    <ts:origins>
      <ts:token-id bitmask="000000000000000000000000000000000000000000FF00000000000000000000" as="uint">
        <ts:mapping>
          <ts:option key="0">
            <ts:value>Devcon5 Tickets </ts:value>
          </ts:option>
        </ts:mapping>
      </ts:token-id>
    </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="section" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <ts:origins>
        <ts:token-id bitmask="0000000000000000000000000000000000000000000000FFFFFFFFFF00000000" as="utf8">
        </ts:token-id>
      </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="locality" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <ts:origins>
        <ts:ethereum function="getLocality" contract="Devcon5" as="utf8">
          <ts:data>
            <ts:uint256 ref="tokenId"/>
          </ts:data>
        </ts:ethereum>
      </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="time" syntax="1.3.6.1.4.1.1466.115.121.1.24">
      <ts:name>
        <ts:string xml:lang="en">Time</ts:string>
        <ts:string xml:lang="zh">时间</ts:string>
        <ts:string xml:lang="es">Tiempo</ts:string>
        <ts:string xml:lang="ru">время</ts:string>
      </ts:name>
      <ts:origins>
        <ts:token-id bitmask="0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000000" as="utf8">
        </ts:token-id>
      </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="expired" syntax="1.3.6.1.4.1.1466.115.121.1.7"> <!-- boolean -->
      <ts:origins>
        <ts:ethereum function="isExpired" contract="Devcon5" as="bool">
          <ts:data>
            <ts:uint256 ref="tokenId"/>
          </ts:data>
        </ts:ethereum>
      </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="street" syntax="1.3.6.1.4.1.1466.115.121.1.15"> <!-- string -->
      <ts:origins>
        <ts:ethereum function="getStreet" contract="Devcon5" as="utf8">
          <ts:data>
            <ts:uint256 ref="tokenId"/>
          </ts:data>
        </ts:ethereum>
      </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="building" syntax="1.3.6.1.4.1.1466.115.121.1.15"> <!-- string -->
      <ts:origins>
        <ts:ethereum function="getBuildingName" contract="Devcon5" as="utf8">
          <ts:data>
            <ts:uint256 ref="tokenId"/>
          </ts:data>
        </ts:ethereum>
      </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="state" syntax="1.3.6.1.4.1.1466.115.121.1.15"> <!-- string -->
      <ts:origins>
        <ts:ethereum function="getState" contract="Devcon5" as="utf8">
          <ts:data>
            <ts:uint256 ref="tokenId"/>
          </ts:data>
        </ts:ethereum>
      </ts:origins>
    </ts:attribute-type>

    <ts:attribute-type id="numero" syntax="1.3.6.1.4.1.1466.115.121.1.27">
      <ts:origins>
        <ts:token-id bitmask="000000000000000000000000000000000000000000FFFF000000000000000000" as="uint"/>
      </ts:origins>
    </ts:attribute-type>

</ts:attribute-types>
</ts:token>

=== AlphaWallet/Tokenscript/examples/dai/dai.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tokenscript  [
        <!ENTITY style SYSTEM "shared.css">
        ]>
<ts:token xmlns:ts="http://tokenscript.org/2019/05/tokenscript"
          xmlns="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://tokenscript.org/2019/05/tokenscript ../../schema/tokenscript.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          custodian="false"
>
    <ts:name xml:lang="en">DAI</ts:name>
    <ts:name xml:lang="zh">代幣</ts:name>
    <ts:contract interface="erc20" label="dai">
        <ts:address network="1"></ts:address>
    </ts:contract>
    <ts:cards>
        <ts:token-card>
            <ts:view-iconified/>
            <ts:view>
                <div id="dai"/>
            </ts:view>
        </ts:token-card>
        <ts:action>
            <ts:name xml:lang="en">Transfer to xDAI</ts:name>
            <ts:attribute-type id="amount" syntax="1.3.6.1.4.1.1466.115.121.1.36">
                <ts:name xml:lang="en">Amount in DAI</ts:name>
                <ts:name xml:lang="zh">代幣金額</ts:name>
                <ts:origins></ts:origins>
            </ts:attribute-type>
            <ts:view/>
        </ts:action>
    </ts:cards>
    <ts:attribute-types>
        <ts:attribute-type id="balance" syntax="1.3.6.1.4.1.1466.115.121.1.36">
            <ts:origins>
                <ts:ethereum-function name="balanceOf" contract="dai">
                    <ts:inputs>
                        <ts:uint256 ref="walletAddress"/>
                    </ts:inputs>
                </ts:ethereum-function>
            </ts:origins>
        </ts:attribute-type>
    </ts:attribute-types>
</ts:token>

=== AlphaWallet/Tokenscript/contrib/wizard/erc-templates/erc20/erc20.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE token  [
    <!ENTITY style SYSTEM "shared.css">
    <!ENTITY approve.en SYSTEM "approve.en.shtml">
    <!ENTITY transferFrom.en SYSTEM "transferFrom.en.shtml">
]>
<ts:token xmlns:ts="http://tokenscript.org/2019/05/tokenscript"
          xmlns="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://tokenscript.org/2019/05/tokenscript ../../schema/tokenscript.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          custodian="false"
>
    <ts:name>
        <ts:plurals xml:lang="en">
            <ts:string quantity="one">Token</ts:string>
            <ts:string quantity="many">Tokens</ts:string>
        </ts:plurals>
    </ts:name>
    <!-- Since it is defined as erc20 here, you will not need to have transfer or receive as an action in AlphaWallet -->
    <ts:contract name="token" interface="erc20">
        <ts:address network="1">0x000000000000000000000000000000000000dEaD</ts:address>
    </ts:contract>
    <ts:origins>
        <ts:ethereum contract="token">
        </ts:ethereum>
    </ts:origins>
    <ts:cards>
        <ts:token-card>
            <ts:view-iconified/>
            <ts:view>
            </ts:view>
        </ts:token-card>
        <ts:action>
            <ts:name>
                <ts:string xml:lang="en">Transfer from</ts:string>
            </ts:name>
            <ts:attribute-type id="amount" syntax="1.3.6.1.4.1.1466.115.121.1.36">
                <ts:name>
                    <ts:string xml:lang="en">Amount in token</ts:string>
                    <ts:string xml:lang="zh">代幣金額</ts:string>
                </ts:name>
                <ts:origins>
                    <!-- e18 is a hard coded multiplier.
                    rationale for hardcoding: avoiding over-design  -->
                    <ts:user-entry as="e18"/>
                </ts:origins>
            </ts:attribute-type>
            <ts:attribute-type id="from" syntax="1.3.6.1.4.1.1466.115.121.1.36">
                <ts:name>
                    <ts:string xml:lang="en">from</ts:string>
                </ts:name>
                <ts:origins>
                    <!-- e18 is a hard coded multiplier.
                    rationale for hardcoding: avoiding over-design  -->
                    <ts:user-entry as="e18"/>
                </ts:origins>
            </ts:attribute-type>
            <ts:attribute-type id="to" syntax="1.3.6.1.4.1.1466.115.121.1.36">
                <ts:name>
                    <ts:string xml:lang="en">to</ts:string>
                </ts:name>
                <ts:origins>
                    <!-- e18 is a hard coded multiplier.
                    rationale for hardcoding: avoiding over-design  -->
                    <ts:user-entry as="e18"/>
                </ts:origins>
            </ts:attribute-type>
            <ts:transaction>
                <ts:ethereum function="transferFrom" contract="token">
                    <ts:data>
                        <ts:address ref="from"/>
                        <ts:address ref="to"/>
                        <ts:uint256 ref="amount"/>
                    </ts:data>
                </ts:ethereum>
            </ts:transaction>
            <style type="text/css">&style;</style>
            <ts:view>&transferFrom.en;</ts:view>
        </ts:action>
        
        <ts:action>
            <ts:name>
                <ts:string xml:lang="en">Approve</ts:string>
            </ts:name>
            <ts:attribute-type id="amount" syntax="1.3.6.1.4.1.1466.115.121.1.36">
                <ts:name>
                    <ts:string xml:lang="en">Amount in token</ts:string>
                    <ts:string xml:lang="zh">代幣金額</ts:string>
                </ts:name>
                <ts:origins>
                    <!-- e18 is a hard coded multiplier.
                    rationale for hardcoding: avoiding over-design  -->
                    <ts:user-entry as="e18"/>
                </ts:origins>
            </ts:attribute-type>
            <ts:attribute-type id="spender" syntax="1.3.6.1.4.1.1466.115.121.1.36">
                <ts:name>
                    <ts:string xml:lang="en">Amount in token</ts:string>
                    <ts:string xml:lang="zh">代幣金額</ts:string>
                </ts:name>
                <ts:origins>
                    <!-- e18 is a hard coded multiplier.
                    rationale for hardcoding: avoiding over-design  -->
                    <ts:user-entry as="e18"/>
                </ts:origins>
            </ts:attribute-type>
            <ts:transaction>
                <ts:ethereum function="approve" contract="token">
                    <ts:data>
                        <ts:address ref="spender"/>
                        <ts:uint256 ref="amount"/>
                    </ts:data>
                </ts:ethereum>
            </ts:transaction>
            <style type="text/css">&style;</style>
            <ts:view>&approve.en;</ts:view>
        </ts:action>
    </ts:cards>

    <ts:attribute-types>

        <ts:attribute-type id="balance" syntax="1.3.6.1.4.1.1466.115.121.1.36">
            <ts:name>
                <ts:string xml:lang="en">token-Balance</ts:string>
            </ts:name>
            <ts:origins>
                <ts:ethereum function="balanceOf" contract="token" as="uint">
                    <ts:data>
                        <ts:address ref="ownerAddress"/>
                    </ts:data>
                </ts:ethereum>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="totalSupply" syntax="1.3.6.1.4.1.1466.115.121.1.36">
            <ts:name>
                <ts:string xml:lang="en">token-Balance</ts:string>
            </ts:name>
            <ts:origins>
                <ts:ethereum function="totalSupply" contract="token" as="uint">
                </ts:ethereum>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="allowance" syntax="1.3.6.1.4.1.1466.115.121.1.36">
            <ts:name>
                <ts:string xml:lang="en">Allowance</ts:string>
            </ts:name>
            <ts:origins>
                <ts:ethereum function="allowance" contract="token" as="uint">
                    <ts:data>
                        <ts:address ref="owner"/>
                        <ts:address ref="spender"/>
                    </ts:data>
                </ts:ethereum>
            </ts:origins>
        </ts:attribute-type>

    </ts:attribute-types>

</ts:token>

=== AlphaWallet/Tokenscript/examples/AliPay/Tour Package A/TourA.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE token  [
        <!ENTITY TourA.en SYSTEM "TourA.en.shtml">
        <!ENTITY style SYSTEM "shared.css">
        ]>
<ts:token xmlns:ts="http://tokenscript.org/2019/10/tokenscript"
          xmlns="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://tokenscript.org/2019/10/tokenscript http://tokenscript.org/2019/10/tokenscript.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          custodian="false"
>
    <ts:name>
        <ts:plurals xml:lang="en">
            <ts:string quantity="one">Tour A Package</ts:string>
            <ts:string quantity="other">Tour A Packages</ts:string>
        </ts:plurals>
    </ts:name>

    <ts:contract name="TourA" interface="erc721">
        <ts:address network="100">0xec78db1c7244854420a2d8d8d8349c646ac60e06</ts:address>
    </ts:contract>

    <ts:origins>
        <!-- Define the contract which holds the token that the user will use -->
        <ts:ethereum contract="TourA">
        </ts:ethereum>
    </ts:origins>

    <ts:cards>
        <ts:token-card>
            <style type="text/css">&style;</style>
            <ts:view-iconified xml:lang="en">
                &TourA.en;
            </ts:view-iconified>
            <ts:view xml:lang="en">
                &TourA.en;
            </ts:view>
        </ts:token-card>
    </ts:cards>

    <ts:attribute-types>

        <ts:attribute-type id="time" syntax="1.3.6.1.4.1.1466.115.121.1.24">
            <ts:name>
                <ts:string xml:lang="en">Time</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000" as="utf8">
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="locality" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">City</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="000000000000000000000000000000000000FF00000000000000000000000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">Wellington</ts:value>
                        </ts:option>
                        <ts:option key="2">
                            <ts:value xml:lang="en">London</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="venue" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">Venue</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="00000000000000000000000000000000000000FF000000000000000000000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">Seven wonders of the world</ts:value>
                        </ts:option>
                        <ts:option key="2">
                            <ts:value xml:lang="en">Red Rocks</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="countryA" syntax="1.3.6.1.4.1.1466.115.121.1.26">
            <!-- Intentionally avoid using countryName
         (SYNTAX 1.3.6.1.4.1.1466.115.121.1.11) per RFC 4519
             CountryName is two-characters long, not 3-characters.
         -->
            <ts:name>
                <ts:string xml:lang="en">From</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="0000000000000000000000000000000000000000FFFFFF000000000000000000" as="utf8"/>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="countryB" syntax="1.3.6.1.4.1.1466.115.121.1.26">
            <ts:name>
                <ts:string xml:lang="en">To</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="0000000000000000000000000000000000000000000000FFFFFF000000000000" as="utf8"/>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="category" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">Cat</ts:string>
                <ts:string xml:lang="zh">等级</ts:string>
                <ts:string xml:lang="es">Cat</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="000000000000000000000000000000000000000000000000000000FF00000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">Great explorer</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="numero" syntax="1.3.6.1.4.1.1466.115.121.1.27">
            <ts:name>
                <ts:string>№</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="00000000000000000000000000000000000000000000000000000000FFFF00" as="uint"/>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="redeemed" syntax="1.3.6.1.4.1.1466.115.121.1.27">
            <ts:name>
                <ts:string>Redeemed</ts:string>
            </ts:name>
            <ts:origins>
                <ts:ethereum function="redeemed" contract="TourA" as="bool">
                    <ts:data>
                        <ts:uint256 ref="tokenId"/>
                    </ts:data>
                </ts:ethereum>
            </ts:origins>
        </ts:attribute-type>

    </ts:attribute-types>
</ts:token>
