=== AlphaWallet/Tokenscript/schema/tokenscript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://tokenscript.org/2019/05/tokenscript"
           xmlns:xhtml="http://www.w3.org/1999/xhtml"
           xmlns="http://tokenscript.org/2019/05/tokenscript">


  <!-- Importing XML namespace for xml:lang and xml:id -->
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="xml.xsd" />

  <!-- Importing XML Signature namespace. Schema is from
      http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd
  -->
  <xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
        schemaLocation="xmldsig-core-schema.xsd" />

  <!-- Importing XHTML namespace. use xhtml1-strict.xsd to get xhtml:Block -->
  <xs:import namespace="http://www.w3.org/1999/xhtml"
             schemaLocation="xhtml1-strict.xsd"/>
  <xs:element name="token">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="contract"/>
        <xs:element ref="origins"/>
        <xs:element minOccurs="0" ref="selections"/>
        <xs:element ref="cards"/>
        <xs:element minOccurs="0" ref="grouping"/>
        <xs:element minOccurs="0" ref="ordering"/>
        <xs:element ref="attribute-types"/>
      </xs:sequence>
      <xs:attribute name="custodian" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="text"/>
  <xs:complexType name="text" mixed="true">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="plurals"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="plurals">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="string"/>
      </xs:sequence>
      <xs:attribute use="required" ref="xml:lang"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="string">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute ref="xml:lang"/>
          <xs:attribute name="quantity" type="quantity"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="quantity">
    <xs:restriction base="xs:string">
      <xs:enumeration value="zero" />
      <xs:enumeration value="one" />
      <xs:enumeration value="two" />
      <xs:enumeration value="few" />
      <xs:enumeration value="many" />
      <xs:enumeration value="other" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="contract">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="address">
          <xs:complexType mixed="true">
            <xs:attribute name="network" use="required" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" ref="interface"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:ID"/>
      <xs:attribute name="interface" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="interface" type="xs:NCName"/>
  <xs:element name="cards">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="token-card"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="action"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="token-card">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="xhtml:style"/>
        <xs:element ref="view-iconified"/>
        <xs:element ref="view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="action">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element minOccurs="0" ref="attribute-type"/>
        <xs:element minOccurs="0" ref="transaction"/>
        <xs:element minOccurs="0" ref="exclude"/>
        <xs:element minOccurs="0" ref="xhtml:style"/>
        <xs:element ref="view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="include" type="xs:NCName"/>
  <xs:element name="view" type="shtml"/>
  <xs:element name="view-iconified" type="shtml">
  </xs:element>
  <xs:complexType name="shtml">
    <xs:complexContent>
      <xs:extension base="xhtml:Block">
        <xs:attributeGroup ref="xhtml:attrs"/>
        <xs:attribute name="onload" type="xhtml:Script"/>
        <xs:attribute name="onunload" type="xhtml:Script"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="redeem">
    <xs:complexType>
      <xs:attribute name="format" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="exclude">
    <xs:complexType>
      <xs:attribute name="selection"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="feemaster" type="xs:anyURI"/>
  <xs:element name="gateway" type="xs:anyURI"/>
  <xs:element name="prefix" type="xs:anyURI"/>
  <xs:element name="selections">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="selection"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="selection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="filter"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="filter" type="xs:string"/>
  <xs:element name="grouping">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="group"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="consecutive_groups"/>
      </xs:sequence>
      <xs:attribute name="bitmask" use="required"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="consecutive_groups">
    <xs:complexType/>
  </xs:element>
  <xs:element name="ordering">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="order"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="order">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="byName"/>
        <xs:element maxOccurs="unbounded" ref="byValue"/>
      </xs:sequence>
      <xs:attribute name="bitmask" use="required"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="byName">
    <xs:complexType>
      <xs:attribute name="field" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="byValue">
    <xs:complexType>
      <xs:attribute name="field" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute-types">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="attribute-type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute-type">
    <xs:complexType>
      <xs:sequence>
        <!-- name is not needed if the attribute is only used for selection -->
        <xs:element minOccurs="0" ref="name"/>
        <xs:element ref="origins"/>
        <xs:element minOccurs="0" ref="mapping"/>
      </xs:sequence>
      <xs:attribute name="as" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="oid" type="xs:NMTOKEN"/>
      <xs:attribute name="syntax" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="transaction">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element ref="ethereum"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="origins">
    <xs:complexType>
      <xs:all>
        <xs:element minOccurs="0" ref="ethereum"/>
        <xs:element minOccurs="0" ref="user-entry"/>
        <xs:element minOccurs="0" ref="token-id"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="user-entry">
    <xs:complexType>
      <xs:attribute name="as" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="token-id">
    <xs:complexType>
      <xs:attribute name="as" type="xs:NCName"/>
      <xs:attribute name="bitmask"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ethereum">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="inputs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="uint256">
                <xs:complexType >
                  <xs:attribute name="ref" use="required" type="xs:NCName"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="contract" type="xs:IDREF"/>
      <xs:attribute name="function" type="xs:NCName"/>
      <xs:attribute name="as" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="option">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="value">
                <xs:complexType mixed="true">
                  <xs:attribute ref="xml:lang"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" use="required" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlphaWallet/Tokenscript/examples/TicketTemplate/TicketTemplate.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE token  [
        <!ENTITY TicketTemplate.en SYSTEM "TicketTemplate.en.shtml">
        <!ENTITY style SYSTEM "shared.css">
        ]>
<ts:token xmlns:ts="http://tokenscript.org/2019/10/tokenscript"
          xmlns="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://tokenscript.org/2019/10/tokenscript http://tokenscript.org/2019/10/tokenscript.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          custodian="false"
>
    <ts:name>
        <ts:plurals xml:lang="en">
            <ts:string quantity="one">An Example TokenScript Ticket </ts:string>
            <ts:string quantity="other">Some Example TokenScript Tickets</ts:string>
        </ts:plurals>
    </ts:name>

    <!-- need to make your own contract address -->
    <ts:contract name="Ticket Template" interface="erc721">
        <ts:address network="100">0x5e8c614cac6d140fbd5a454f41a1d5dc5da1a218</ts:address>
    </ts:contract>

    <ts:origins>
        <!-- Define the contract which holds the token that the user will use -->
        <ts:ethereum contract="Ticket Template">
        </ts:ethereum>
    </ts:origins>

    <ts:cards>
        <ts:token-card>
            <style type="text/css">&style;</style>
            <ts:view-iconified xml:lang="en">
                &TicketTemplate.en;
            </ts:view-iconified>
            <ts:view xml:lang="en">
                &TicketTemplate.en;
            </ts:view>
        </ts:token-card>
    </ts:cards>

    <!-- Attribute types define what's inside the Tokenscript -->
    <ts:attribute-types>
        <ts:attribute-type id="title" syntax="1.3.6.1.4.1.1466.115.121.1.24">
            <ts:name>
                <ts:string xml:lang="en">TokenScript Template</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000" as="utf8">
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="subtitle" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">A blank template for Tokenscript</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="000000000000000000000000000000000000FF00000000000000000000000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">Shanghai</ts:value>
                        </ts:option>
                        <ts:option key="2">
                            <ts:value xml:lang="en">London</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="footer" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">You can fill this in later</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="00000000000000000000000000000000000000FF000000000000000000000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">Shanghai Pudong Airport</ts:value>
                        </ts:option>
                        <ts:option key="2">
                            <ts:value xml:lang="en">London Heathrow Airport</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

       
    </ts:attribute-types>
</ts:token>

=== AlphaWallet/Tokenscript/examples/AliPay/Summit/Summit.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE token  [
        <!ENTITY Summit.en SYSTEM "Summit.en.shtml">
        <!ENTITY style SYSTEM "shared.css">
        ]>
<ts:token xmlns:ts="http://tokenscript.org/2019/10/tokenscript"
          xmlns="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://tokenscript.org/2019/10/tokenscript http://tokenscript.org/2019/10/tokenscript.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          custodian="false"
>
    <ts:name>
        <ts:plurals xml:lang="en">
            <ts:string quantity="one">Summit Pass</ts:string>
            <ts:string quantity="other">Summit Passes</ts:string>
        </ts:plurals>
    </ts:name>

    <ts:contract name="Summit" interface="erc721">
        <ts:address network="100">0x6b2c1f4f903ce8df4e52e153e4d0a103030787c0</ts:address>
    </ts:contract>

    <ts:origins>
        <!-- Define the contract which holds the token that the user will use -->
        <ts:ethereum contract="Summit">
        </ts:ethereum>
    </ts:origins>

    <ts:cards>
        <ts:token-card>
            <style type="text/css">&style;</style>
            <ts:view-iconified xml:lang="en">
                &Summit.en;
            </ts:view-iconified>
            <ts:view xml:lang="en">
                &Summit.en;
            </ts:view>
        </ts:token-card>
    </ts:cards>

    <ts:attribute-types>

        <ts:attribute-type id="time" syntax="1.3.6.1.4.1.1466.115.121.1.24">
            <ts:name>
                <ts:string xml:lang="en">Time</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000" as="utf8">
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="locality" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">City</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="000000000000000000000000000000000000FF00000000000000000000000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">Shanghai</ts:value>
                        </ts:option>
                        <ts:option key="2">
                            <ts:value xml:lang="en">London</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="venue" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">Venue</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="00000000000000000000000000000000000000FF000000000000000000000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">MGM Grand</ts:value>
                        </ts:option>
                        <ts:option key="2">
                            <ts:value xml:lang="en">ICC centre</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="countryA" syntax="1.3.6.1.4.1.1466.115.121.1.26">
            <!-- Intentionally avoid using countryName
         (SYNTAX 1.3.6.1.4.1.1466.115.121.1.11) per RFC 4519
             CountryName is two-characters long, not 3-characters.
         -->
            <ts:name>
                <ts:string xml:lang="en">From</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="0000000000000000000000000000000000000000FFFFFF000000000000000000" as="utf8"/>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="countryB" syntax="1.3.6.1.4.1.1466.115.121.1.26">
            <ts:name>
                <ts:string xml:lang="en">To</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="0000000000000000000000000000000000000000000000FFFFFF000000000000" as="utf8"/>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="category" syntax="1.3.6.1.4.1.1466.115.121.1.15">
            <ts:name>
                <ts:string xml:lang="en">Cat</ts:string>
                <ts:string xml:lang="zh">等级</ts:string>
                <ts:string xml:lang="es">Cat</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="000000000000000000000000000000000000000000000000000000FF00000000" as="uint">
                    <ts:mapping>
                        <ts:option key="1">
                            <ts:value xml:lang="en">Speaker pass</ts:value>
                        </ts:option>
                        <ts:option key="2">
                            <ts:value xml:lang="en">Volunteer pass</ts:value>
                        </ts:option>
                    </ts:mapping>
                </ts:token-id>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="numero" syntax="1.3.6.1.4.1.1466.115.121.1.27">
            <ts:name>
                <ts:string>№</ts:string>
            </ts:name>
            <ts:origins>
                <ts:token-id bitmask="00000000000000000000000000000000000000000000000000000000FFFF00" as="uint"/>
            </ts:origins>
        </ts:attribute-type>

        <ts:attribute-type id="redeemed" syntax="1.3.6.1.4.1.1466.115.121.1.27">
            <ts:name>
                <ts:string>Redeemed</ts:string>
            </ts:name>
            <ts:origins>
                <ts:ethereum function="redeemed" contract="Summit" as="bool">
                    <ts:data>
                        <ts:uint256 ref="tokenId"/>
                    </ts:data>
                </ts:ethereum>
            </ts:origins>
        </ts:attribute-type>

    </ts:attribute-types>
</ts:token>
